#default: &default
#  adapter: sqlite3
#  pool: <%#= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: web615-lab4-development
  host: db
  username: postgres
  password:

test:
  <<: *default
  database: web615-lab4-test
  host: <%= ENV['POSTGRES_HOST'] ||='db' %>
  username: postgres
  password: web615-lab4-test

production:
  <<: *default
  database: web615-lab4
  username: web615-lab4
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
