default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  # timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  host: db
  username: postgres
  password:

test:
  <<: *default
  # database: db/test.sqlite3
  database: bleater-test
  host: <%= ENV['POSTGRES_HOST'] ||= 'db' %>
  username: <%= ENV['POSTGRES_USER'] ||= 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] ||= '' %>

production:
  <<: *default
  database: bleater
  username: bleater
  password: <%= ENV['MYAPP_DATABASE_PASSWORDT'] %>